version: '3.3'

services:
    db:
     image: mariadb:10.4.7
     volumes:
       - db_data:/var/lib/mysql
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_ROOT_PASSWORD: gsviec
       MYSQL_DATABASE: gsviec
       MYSQL_USER: gsviec
       MYSQL_PASSWORD: gsviec
     ports:
       - 3307:3306
    php:
     depends_on:
       - db
       - redis
     image: gsviec/php:7.3-alpine
     ports:
       - "80:80"
     volumes:
      - ./:/app
     env_file:
       - .env
    phpmyadmin:
      restart: 'no'
      image: phpmyadmin/phpmyadmin:4.6
      depends_on:
        - db
      ports:
        - "9090:80"
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_USER: root
        PMA_PASSWORD: gsviec
    redis:
      image: redis:alpine
      ports:
        - '6378:6379'
    flyway:
      image: gsviec/flyway
      volumes:
        - ./database:/flyway/sql
      depends_on:
        - db
volumes:
    db_data:
